// Problem2.cpp : Defines the entry point for the console application.

#include "stdafx.h"

/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

int _tmain(int argc, _TCHAR* argv[])
{
	unsigned long long sum = 0;
	unsigned long long one = 1;
	unsigned long long two = 2;
	unsigned long long next = 0;

	while (two < 4000000)
	{
		if ((two % 2) == 0)
		{
			sum += two;
		}
		next = one + two;
		one = two;
		two = next;
	}

	printf("%d\n", sum);
	return 0;
}
